config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :customers, :controllers => { registrations: 'registrations' }
  devise_for :admins
  
  resources :payments
  resources :products
  resources :order_lines, only: [:create, :update, :destroy]
  resource :carts, only: [:index, :show]

  post "/products/:id/add_to_cart" => "cart#add_to_cart", as: "add_to_cart"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, :lastname, presence: true
  
end

app/models/order.rb
class Order < ActiveRecord::Base

  enum status: [ :cart, :completed, :rejected, :cancelled ]

  before_validation :order_no, :total
  
  has_many :order_lines
  belongs_to :customer

  validates :customer, :order_no, :status, :total, presence: true
  validates :total, numericality: { greater_than_or_equal_to: 0 }

  def order_no
    self.order_no = SecureRandom.urlsafe_base64
  end

  def total
    order_total = 0
    unless self.order_lines.nil?
      self.order_lines.each do |order_line|
        order_total += order_line.total_price
      end
    end
    self.total = order_total
  end
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base

  before_validation :total_price

  belongs_to :order
  belongs_to :product

  validates :product, :order, :qty, :unit_price, :total_price, presence: true
  validates :qty, numericality: { greater_than_or_equal_to: 1 }
  validates :unit_price, numericality: { greater_than_or_equal_to: 1.0 }
  
  def total_price
    self.total_price = qty * unit_price
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base

  scope :is_enabled, -> { where(status: true) }

  has_many :order_lines

  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1.0 }
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_order

  def after_sign_in_path_for(resource)
    products_path
  end

  def current_order
    if session[:order_id].nil?
      Order.new do |u|
        u.customer = current_customer
        u.status = "cart"
      end
    else
      Order.find(session[:order_id])
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_customer!

  def show
    @order = current_order
    respond_to do |format|
      format.html
      format.json { render json: @order }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  STATUS_OK = "ok".freeze
  STATUS_REJECT = "reject".freeze

  def new
    response = PaymentGatewayService.process_payment
    order = current_order
    if response == STATUS_OK
      if order.update(status: "completed")
        session[:order_id] = nil
        redirect_to carts_path, notice: "Order no #{order.order_no} is confirmed."
      else
        redirect_to carts_path, alert: "Error - cannot make payment to the order no #{order.order_no}"
      end
    elsif response == STATUS_REJECT
      if order.update(status: "rejected")
        redirect_to carts_path, notice: "Order no #{order.order_no} is rejected."
      else
        redirect_to carts_path, alert: "Error - cannot make payment to the order no #{order.order_no}"
      end
    else
      redirect_to carts_path, alert: "Error - with payment"
    end
  rescue => e
    log_error(e)
  end

  private

  def log_error(error)
    Rails.logger.error(error.to_s)
    Rails.logger.error(error.backtrace.join("\n"))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if admin_signed_in?
      @products = Product.all
    else
      @products = Product.is_enabled
    end    
    @order_line = current_order.order_lines.new
    respond_to do |format|
        format.html
        format.json
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:description, :name, :price, :status)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:customer).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:customer).permit(:firstname,
                                     :lastname, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="message">
       <div class="alert alert-alert" role="alert">
        <h4>#{sentence}</h4>
        #{messages}
       </div>
    </div>
    HTML

    html.html_safe
  end
end

app/views/admin/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Name</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.description %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.status %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/carts/show.html.erb
<% if @order.order_lines.empty? %>
  <div class="container">
    <p>You have no items in shopping cart.</p>
  </div>
<% else %>
  <div class="cart">
    <div class="container">
      <h1>Order Details</h1>
      <table class="table table-striped table-hover table-bordered">
        <tbody>
        <tr>
          <th>Item</th>
          <th>Quantity</th>
          <th>Unit Price</th>
          <th>Total Price</th>
          <th>Remove</th>
        </tr>
        <% for order_line in @order.order_lines  %>
            <tr>
              <td><%= order_line.product.name %></td>
              <td><%= order_line.qty %></td>
              <td><%= number_to_currency(order_line.unit_price) %></td>
              <td><%= number_to_currency(order_line.total_price) %></td>
              <td><%= link_to 'remove', order_line_path(order_line), method: "DELETE" %></td>
            </tr>
        <% end %>
        <tr>
          <th colspan="3"><span class="pull-right">Total</span></th>
          <th><%= number_to_currency(@order.total) %></th>
        </tr>
        </tbody>
      </table>
      <div class="col-md-8">
        <th class="bg-none" colspan="4"><%= link_to 'Payment', new_payment_path, class: "pull-right btn btn-cart" %></th>
      </div>
    </div>  
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container">
  <h1>Welcome to Walmart</h1>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default bg-aqua" role="navigation">
  <div class="container-fluid">
  
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="navbar-header">
        <%= link_to(image_tag("home", class:"navbar-brand" ), root_path) %>

      </div>
      <ul class="nav navbar-nav navbar-left">
        <% if admin_signed_in? %>
          <li><%= link_to 'Products', products_path %></li>
        <% elsif customer_signed_in? %>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to "#{ current_order.order_lines.size } Cart", carts_path %></li>
        <% end %> 
      </ul>
 
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to('Logout', destroy_admin_session_path, :method => :delete) %></li>
        <% elsif customer_signed_in? %>
          <li><%= link_to('Logout', destroy_customer_session_path, :method => :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_customer_session_path)  %></li>
          <li><%= link_to('Register', new_customer_registration_path)  %></li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Walmart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <% flash.each do |key, value| %>
      <div class="message">
        <div class="alert alert-<%= key %>" role="alert">
          <a class="close" href="#">&times</a>
          <strong><%= value %></strong>
        </div>
      </div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :name, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :description, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :price, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.number_field :price, min:0, class: "form-control" %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :status, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.check_box :status %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <div class="col-lg-4">
      <%= f.submit "Submit", class:"btn btn-lg btn-primary btn-block btn-aqua" %>
    </div>
  </div>
<% end %>

app/views/products/_form_new.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :name, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :description, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :price, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.number_field :price, value:0, min:0, class: "form-control" %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <%= f.label :status, class: "col-lg-2" %>
    <div class="col-lg-4">
      <%= f.check_box :status %>
    </div>
  </div>

  <div class="col-lg-12 form-group margin50">
    <div class="col-lg-4">
      <%= f.submit "Submit", class:"btn btn-lg btn-primary btn-block btn-aqua" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1>Editing Product</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="product">
  <p class="font-h1">
    Listing Products
  </p>
  
  <% if admin_signed_in? %>
    <%= link_to 'Add Product', new_product_path, class: "btn btn-aqua" %>
  <% end %>
  

  <% @products.each do |product| %>
  
    <div class="add-to-cart item-row">
      <div class="col-md-2">
        <td><%= image_tag("images-#{(product.id%8)+1}", class: "image-url") %></td>
      </div>
      <div class="col-md-3">
        <td>
          <br>
          <ul><%= link_to product.name, product %></ul>
          <ul><%= product.description %></ul> 
        </td>
      </div>
      <div class="col-md-2">
        <h2><%= number_to_currency(product.price) %></h2>
      </div>
      <%= form_for @order_line do |f| %>
          <div class="col-md-2">
            <% if customer_signed_in? %>

              
              <label>Quantity:</label>
              <%= f.number_field :qty, value: 1, class: "form-control", min: 1 %>
              
              <%= f.submit "Add to Cart", class: "btn btn-cart" %>
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.hidden_field :unit_price, value: product.price %>
            <% end %>

           
          
          <% if admin_signed_in? %>
            <td>
              <br>
              <ul>
              <% if(product.status) %>
                Enable
              <% else %>
                Disable
              <% end %>  
              </ul>
              <ul><%= link_to 'Edit', edit_product_path(product) %></ul>
              <ul><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></ul>
            </td>
          <% end %> 
          </div> 
      <% end %>
    </div>
    <!-- </div> -->
  <% end %>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>

  <%= render 'form_new' %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @product.status %>
  </p>

  <p>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
  </p>
</div>